-- THIS FILE IS AUTO-GENERATED, WOULD BE OVERWRITTEN BY GUI-EDITOR
local component = require '@common.base.gui.component'
local bind = component.bind
local call = component.call
local gui_pkg = require '@common.base.gui.package'
local get_text = gui_pkg.get_text() or get_text
local on_player_prop = require '@common.base.gui.on_player_prop'
local on_unit_prop = require '@common.base.gui.on_unit_prop'
local ctrl_wrapper = require '@common.base.gui.ctrl_wrapper'


local lib_game_options = require '@lib_game_options.component'
local smallcard_unit_attr_panel = require '@smallcard_unit_attr_panel.component'
local lib_control = require '@lib_control.component'
local smallcard_inventory = require '@smallcard_inventory.component'
local smallcard_choose_one = require '@smallcard_choose_one.component'
local gameui = require '@gameui.component'

return gui_pkg.page_template {
    flatten_template = {
        ctrl_wrapper.panel {
            __EDIT_TIME = {
                enable_layout_grid = true,
                layout_grid_size = 30,
                lock = true,
            },
            color = 'rgba(0,0,0,0)',
            image = '',
            layout = {
                grow_height = 1,
                grow_width = 1,
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
            },
            name = 'MainPage',
            show = true,
        },0,
        lib_game_options.设置按钮 {
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 100,
                ratio = {},
                relative = {
                    [1] = -100,
                    [2] = 200,
                },
                row_self = 'end',
                width = 100,
            },
            name = '设置按钮1',
            show = false,
        },1,
        smallcard_inventory.背包入口 {
            layout = {
                ratio = {},
                relative = {
                    [1] = -2098.3106689453,
                    [2] = 40.52099609375,
                },
            },
            name = '背包入口2',
            show = false,
        },1,
        smallcard_choose_one.N选1_整体面板 {
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
            },
            name = 'N选1_整体面板2',
            show = false,
        },1,
        smallcard_unit_attr_panel.单位属性面板 {
            bind_unit = 0,
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 72,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = 714,
            },
            name = '单位属性面板3',
            show = false,
        },1,
        gameui.xf_2_rect {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            decoration_image = '',
            decoration_layout_left = {
                margin = {
                    left = 6,
                },
                row_self = 'start',
            },
            decoration_layout_right = {
                margin = {
                    right = 6,
                },
                row_self = 'end',
            },
            image = '@busiyixiantu_5n1b/image/_0002_技能暴击.png',
            is_decoration = false,
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                height = 1091.0019814927,
                position = {},
                ratio = {},
                relative = {
                    [1] = -1.0,
                    [2] = 2.5,
                },
                row_self = 'center',
                width = 2346.8472047219,
            },
            name = '开始界面',
            rotate = 0,
            show = false,
            style = 'image/rect/面板-科技2.png',
            transition = {
                position = {
                    func = {
                        [1] = 0,
                        [2] = 0,
                        [3] = 1,
                        [4] = 1,
                    },
                    time = 0,
                },
            },
        },1,
        gameui.xf_2_rect {
            border = {
                bottom = 45,
                left = 45,
                right = 45,
                top = 45,
            },
            decoration_image = '',
            decoration_layout_left = {
                margin = {
                    left = 6,
                },
                row_self = 'start',
            },
            decoration_layout_right = {
                margin = {
                    right = 6,
                },
                row_self = 'end',
            },
            is_decoration = false,
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                height = 1091.0019814927,
                position = {},
                ratio = {},
                relative = {
                    [1] = -1.0,
                    [2] = -5.0,
                },
                row_self = 'center',
                width = 2346.8472047219,
            },
            name = '主界面',
            rotate = 0,
            show = false,
            style = 'image/rect/面板-科技2.png',
            transition = {
                position = {
                    func = {
                        [1] = 0,
                        [2] = 0,
                        [3] = 1,
                        [4] = 1,
                    },
                    time = 0,
                },
            },
        },1,
        ctrl_wrapper.label {
            font = {
                bold = true,
                color = 'rgba(192, 176, 155, 1.0000)',
                family = 'SourceHanSerif',
                size = 50,
            },
            layout = {
                col_self = 'start',
                height = 72,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 90,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'label1b',
            text = '选择技能',
        },4,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_choose_one/image/title_l.png',
            layout = {
                col_self = 'start',
                height = 32.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = -432.0,
                    [2] = 110.0,
                },
                row_self = 'center',
                width = 550.0,
            },
            name = 'panel1a',
        },4,
        ctrl_wrapper.panel {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_choose_one/image/title_r.png',
            layout = {
                col_self = 'start',
                height = 32.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 432,
                    [2] = 110.0,
                },
                row_self = 'center',
                width = 551.0,
            },
            name = 'panel1a',
        },4,
        smallcard_choose_one.N选1_选择面板 {
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
            },
            name = 'N选1_选择面板5',
        },4,
        smallcard_choose_one.N选1_确认按钮 {
            border = {
                bottom = 25.130434782609,
                left = 29.565217391304,
                right = 29.565217391304,
                top = 14.782608695652,
            },
            image = '@smallcard_choose_one/image/button.png',
            layout = {
                col_self = 'end',
                height = 99.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -115,
                },
                row_self = 'center',
                width = 408.0,
            },
            name = 'N选1_确认按钮3',
            text = '确定',
        },4,
        smallcard_choose_one.N选1_关闭面板 {
            layout = {
                col_self = 'start',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = -100.0,
                    [2] = 100.0,
                },
                row_self = 'end',
                width = 48,
            },
            name = 'N选1_关闭面板4',
        },4,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '护甲',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性icon (1).png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = 222,
                    [2] = 0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },5,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '攻击',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性icon.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = 60,
                    [2] = 0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },5,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '移动速度',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性icon (2).png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = 384,
                    [2] = 0.0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },5,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '生命上限',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@smallcard_unit_attr_panel/image/属性=魔法.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = 546,
                    [2] = 0.0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },5,
        gameui.sci_3_major_btn {
            active_image = 'image/btn/sci_1_major_active.png',
            border = {
                bottom = 30,
                left = 40,
                right = 40,
                top = 30,
            },
            image = 'image/btn/sci_1_major.png',
            layout = {
                col_self = 'center',
                grow_height = 0.42685185185185,
                grow_width = 0.12820512820513,
                height = 461.9948748667,
                position = {},
                ratio = {},
                relative = {
                    [1] = 773.0,
                    [2] = 3.0,
                },
                row_self = 'center',
                width = 300,
            },
            name = '按钮-科技1-主要29',
            show = true,
            text = '',
            text_color = '#000000',
            text_opacity = 1,
        },6,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,0.784)',
            layout = {
                col_self = 'start',
                height = 105.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 4.0,
                    [2] = 630.0,
                },
                row_self = 'start',
                width = 125.18133544922,
            },
            name = '体力',
            show = true,
        },7,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,0.784)',
            layout = {
                col_self = 'start',
                height = 105.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 5.0,
                    [2] = 146.0,
                },
                row_self = 'start',
                width = 125.94506835938,
            },
            name = '体力',
            show = true,
        },7,
        ctrl_wrapper.label {
            font = {
                color = 'rgba(8, 0, 0, 1.0000)',
                size = 80,
                wrap = false,
            },
            layout = {
                col_self = 'start',
                height = 326.73693847656,
                position = {},
                ratio = {},
                relative = {
                    [1] = 4.0,
                    [2] = 751.0,
                },
                row_self = 'start',
                width = 125.0,
            },
            name = '玩家名字',
            rotate = -90,
            show = true,
            text = '文本',
        },7,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,0.784)',
            layout = {
                col_self = 'start',
                height = 105.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 6.0,
                    [2] = 394.0,
                },
                row_self = 'start',
                width = 126.70880126953,
            },
            name = '体力',
            show = true,
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 103.68931929598,
                position = {},
                ratio = {},
                relative = {
                    [1] = 946.28173828125,
                    [2] = 60.399169921875,
                },
                row_self = 'start',
                width = 650.9385044692,
            },
            name = '镇守天门',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 251.54260792173,
                position = {},
                ratio = {},
                relative = {
                    [1] = 249.19738769531,
                    [2] = 664.60522460938,
                },
                row_self = 'start',
                width = 312.98813046749,
            },
            name = '灵山',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 251.54260792173,
                position = {},
                ratio = {},
                relative = {
                    [1] = 855.0,
                    [2] = 314.0,
                },
                row_self = 'start',
                width = 312.98813046749,
            },
            name = '核心玩法',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 251.54260792173,
                position = {},
                ratio = {},
                relative = {
                    [1] = 1580.8253173828,
                    [2] = 663.47143554688,
                },
                row_self = 'start',
                width = 312.98813046749,
            },
            name = '宗门建设',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 251.54260792173,
                position = {},
                ratio = {},
                relative = {
                    [1] = 1759.3193359375,
                    [2] = 213.92016601562,
                },
                row_self = 'start',
                width = 312.98813046749,
            },
            name = '斩妖除魔',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 150,
                position = {},
                ratio = {},
                relative = {
                    [1] = 2220.0,
                    [2] = 930.0,
                },
                row_self = 'start',
                width = 120,
            },
            name = '待定1',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 150,
                position = {},
                ratio = {},
                relative = {
                    [1] = 2220.0,
                    [2] = 780.0,
                },
                row_self = 'start',
                width = 120,
            },
            name = '待定1',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 240,
                position = {},
                ratio = {},
                relative = {
                    [1] = 2220.0,
                    [2] = 540.0,
                },
                row_self = 'start',
                width = 120,
            },
            name = '待定1',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 180,
                position = {},
                ratio = {},
                relative = {
                    [1] = 2220.0,
                    [2] = 360.0,
                },
                row_self = 'start',
                width = 120,
            },
            name = '待定1',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 180,
                position = {},
                ratio = {},
                relative = {
                    [1] = 2220.0,
                    [2] = 180.0,
                },
                row_self = 'start',
                width = 120,
            },
            name = '待定1',
        },7,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 180,
                position = {},
                ratio = {},
                relative = {
                    [1] = 2220.0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 120,
            },
            name = '待定1',
        },7,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = -866,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },11,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = -433,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },11,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },11,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 433,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },11,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 866,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },11,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,0.784)',
            layout = {
                col_self = 'start',
                height = 129.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 26.020202636719,
                    [2] = -129.0,
                },
                row_self = 'start',
                width = 78.979797363281,
            },
            name = 'panel2d',
        },19,
        ctrl_wrapper.label {
            font = {
                color = 'rgba(17, 12, 12, 1.0000)',
                size = 35,
                wrap = false,
            },
            layout = {
                col_self = 'start',
                height = 131.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 26.008117675781,
                    [2] = -131.0,
                },
                row_self = 'start',
                width = 78.991882324219,
            },
            name = '体力信息',
            rotate = -90,
            text = '12/13',
        },19,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,0.784)',
            layout = {
                col_self = 'start',
                height = 129.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 26.020202636719,
                    [2] = -129.0,
                },
                row_self = 'start',
                width = 78.979797363281,
            },
            name = 'panel2d',
        },20,
        ctrl_wrapper.label {
            font = {
                color = 'rgba(17, 12, 12, 1.0000)',
                size = 35,
                wrap = false,
            },
            layout = {
                col_self = 'start',
                height = 131.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 26.008117675781,
                    [2] = -131.0,
                },
                row_self = 'start',
                width = 78.991882324219,
            },
            name = '体力信息',
            rotate = -90,
            text = '12/13',
        },20,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,0.784)',
            layout = {
                col_self = 'start',
                height = 129.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 26.020202636719,
                    [2] = -129.0,
                },
                row_self = 'start',
                width = 78.979797363281,
            },
            name = 'panel2d',
        },22,
        ctrl_wrapper.label {
            font = {
                color = 'rgba(17, 12, 12, 1.0000)',
                size = 35,
                wrap = false,
            },
            layout = {
                col_self = 'start',
                height = 131.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 26.008117675781,
                    [2] = -131.0,
                },
                row_self = 'start',
                width = 78.991882324219,
            },
            name = '体力信息',
            rotate = -90,
            text = '12/13',
        },22,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },34,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
            show = true,
        },34,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },34,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },35,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },35,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },35,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },36,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },36,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },36,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },37,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },37,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },37,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },38,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },38,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },38,
    }
}