{
    "ElementName":"FunctionDefine",
    "actions":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"SetValue",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"",
                "flags":{
                },
                "left":{
                    "ElementName":"Index",
                    "baseValue":{
                        "ElementName":"FunctionCall",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"",
                        "flags":{
                        },
                        "funcSource":{
                            "ElementName":"Source",
                            "targetUninit":{
                                "id":"FunctionDefine:gui_get_part4248698880.0",
                                "packageName":"__client__",
                                "s_or_c":"client"
                            }
                        },
                        "parameters":{
                            "__TYPE":"Array",
                            "contents":[
                                {
                                    "ElementName":"FunctionCall",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"",
                                    "flags":{
                                        "enableDisplayName":true
                                    },
                                    "funcSource":{
                                        "ElementName":"Source",
                                        "targetUninit":{
                                            "id":"FunctionDefine:gui_get_main_page1445330944",
                                            "packageName":"__client__",
                                            "s_or_c":"client"
                                        }
                                    },
                                    "parameters":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    },
                                    "s_or_c":"client",
                                    "staticWarningMsgs":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    },
                                    "typeParameters":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    }
                                },
                                {
                                    "ElementName":"Instant",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"",
                                    "flags":{
                                        "enableDisplayName":true
                                    },
                                    "staticWarningMsgs":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    },
                                    "type":{
                                        "ElementName":"SimpleType",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"字符串",
                                        "flags":{
                                        },
                                        "name":"string",
                                        "staticWarningMsgs":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        }
                                    },
                                    "value":"人物属性主面板"
                                }
                            ]
                        },
                        "s_or_c":"client",
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "typeParameters":{
                            "__TYPE":"Array",
                            "contents":[
                                {
                                    "ElementName":"InstanceType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"",
                                    "flags":{
                                    },
                                    "source":{
                                        "ElementName":"Source",
                                        "targetUninit":{
                                            "id":"Class:_OBJ__gui_ctrl_panel",
                                            "packageName":"__client__",
                                            "s_or_c":"client"
                                        }
                                    },
                                    "staticWarningMsgs":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    },
                                    "typeArgs":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                        "fromOop":true
                    },
                    "indexSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ__gui_ctrl_panel, ClassProperty:show",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "s_or_c":"client",
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "right":{
                    "ElementName":"Instant",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "type":{
                        "ElementName":"SimpleType",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"布尔值",
                        "flags":{
                        },
                        "name":"boolean",
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        }
                    },
                    "value":false
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                }
            }
        ]
    },
    "breakPointInfo":{
        "disabled":false,
        "hasBreakPoint":false,
        "type":2
    },
    "defaultResetParameterCount":0,
    "description":"",
    "displayName":"func",
    "flags":{
        "hideConfig":true,
        "noSelf":true,
        "pop":true,
        "unchangeName":true,
        "unchangeParameter":true
    },
    "id":"FunctionDefine:func:536227670",
    "keyword":"",
    "label":"默认",
    "linkspace":"",
    "name":"func",
    "packageName":"__validator__",
    "parameters":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"ctrl",
                "flags":{
                },
                "id":"Variable:ctrl:3135934693",
                "keyword":"",
                "name":"ctrl",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ__gui_ctrl_label",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"mouse_btn_id",
                "flags":{
                },
                "id":"Variable:mouse_btn_id:3248949930",
                "keyword":"",
                "name":"mouse_btn_id",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"SimpleType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"数值",
                    "flags":{
                    },
                    "name":"number",
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    },
    "rankOrder":0,
    "realReturnType":{
        "ElementName":"SimpleType",
        "breakPointInfo":{
            "disabled":false,
            "hasBreakPoint":false,
            "type":2
        },
        "displayName":"void",
        "flags":{
        },
        "name":"void",
        "staticWarningMsgs":{
            "__TYPE":"Array",
            "contents":{
            }
        }
    },
    "s_or_c":"client",
    "staticWarningMsgs":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "subsections":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "tips":"",
    "typeParameters":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "typeParametersExtends":{
        "__TYPE":"Map",
        "contents":{
        }
    },
    "uiText":"",
    "v2_version":0.500000,
    "variables":{
        "__TYPE":"Array",
        "contents":{
        }
    }
}